package dit.trabajo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class criteriosDNL implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public criteriosDNL() {
    }




}